CREATE TABLE IF NOT EXISTS `upload` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `size` INT(11) NOT NULL,
    `type` VARCHAR(200) NOT NULL,
    `content` TEXT NOT NULL,
    `path` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;
